apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dubbo-admin
  name: dubbo-admin
  namespace: dubbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubbo-admin
  template:
    metadata:
      labels:
        app: dubbo-admin
    spec:
      # If you want to use rbac.yaml, uncomment this.
      # serviceAccountName: dubbo-admin
      containers:
        - name: dubbo-admin
          # Update to your ECR address.
          image: <account-id>.dkr.ecr.<my-region>.amazonaws.com/dubbo-admin:latest
          imagePullPolicy: Always
          env:
            - name: DUBBO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: dubbo
                  key: DUBBO_ROOT_USER
            - name: DUBBO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dubbo
                  key: DUBBO_ROOT_PASSWORD
            - name: NACOS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dubbo
                  key: NACOS_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dubbo
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /config
              name: application-properties
            # - mountPath: /storage
            #   name: dubbo-admin-storage

          # Liveness probes should be higher during initial delays as it takes time for this service to start with MySQL
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            limits:
              memory: "2Gi"
              cpu: "500m"
            requests:
              cpu: 250m
              memory: 1Gi
          securityContext:
            runAsUser: 0
      volumes:
        - name: application-properties
          configMap:
            name: dubbo-admin
        # Uncomment if you want to use pv.yaml & pvc.yaml
        # - name: dubbo-admin-storage
        #   persistentVolumeClaim:
        #     claimName: dubbo-admin-pvc
