apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dubbo-admin-pvc
  namespace: dubbo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3
